### ISSUE TITLE
Relay messaging failing on travis

### ISSUE THREAD

**Issue by robertsdotpm** [Storj/storjnode#21]
======================================================================
FAIL: test_relay_message_full_duplex (tests.network.api.TestNode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/network/api.py", line 265, in test_relay_message_full_duplex
    self.assertTrue(alice_received.isSet())
AssertionError: False is not true

Issue is intermittent. It may just be insufficient timeout for relay interval but the code should be tested in isolation to try reproduce the bug.

**Comment by F483** [comment]
This had to do with the fact that used kadmelia is not thread save and all access must be done from the twisted thread. I have modified the message relay code to account for this and packets should no longer drop because of this.

Fixed in https://github.com/Storj/storjnode/commit/f9224c2893a40bcc9a06018f9d66dd10c0e35abd
