### ISSUE TITLE
Add Support for Config Encryption

### ISSUE THREAD

**Issue by F483** [Storj/storjnode#39]
If --password=SOMETHING_SECURE is pass the config should be encrypted if it is not already.
If it is done on the first command an unencrypted config should never hit the drive.
An additional command change_password should be added so the user can change it.
It may be worth have encryption required and printing the generated password to be used (would also ensure secure passwords).

The main code needed is already implemented in storjnode/encryptedio.py and only needs to be enabled.

This should only be done when the users can edit the config via the cli and/or gui, as editing an encrypted config is difficult (though possible as its compatible with openssl aes-256-cbc).

**Comment by super3** [comment]
@F483 Doesn't this impact usability? This should run in the background and at startup, which means the client it going to have access to the keys.

**Comment by F483** [comment]
The client is ultimately going to need access to keys (at the moment just for authentication). Money will have to be stored on the machine (for change at the very least) and even if its moved to cold storage asap the key will need to be stored somewhere.

To make this as save only one deterministic hot wallet is stored in the config that can be easily recovered and it should also be encrypted.

Security is always a usability trade off and we cannot sacrifice security for the convenience.

**Comment by super3** [comment]
Well storjnode doesn't hold any money. I think it would make sense to have any cold wallet config encrypted. For the cold wallet you don't have to unencrypt, just have the public key around. 

The hot wallet needs to perform many network operations, and maybe be able to pay for fees or transfers automatically. The hot wallet needs to contain a small amount of money which can be accessed without encumbrance(dust level really). Everything extra should be routed to the encrypted cold wallet.

**Comment by robertsdotpm** [comment]
This seems like a very insecure way to handle setting up the encryption. If the password is passed as a command line argument it could be saved to the user's bash_history file which (depending on perms) could allow for privilege escalation by other processes. That's probably why things like ssh don't allow you to pass passwords directly and instead operate in interactive mode for the important stuff (easy to fix this.)

Regarding wallets: Shawn's design [for the farmer] is probably the best we can hope for security-wise (excluding obscure recent developments.) You have enough money around for operating costs (the hot wallet) and move any excessive extra to the cold wallet which will work fine for farmers. Interestingly enough, you could theoretically use a timechain to make a cold wallet gradually thaw over time and trickle small amounts of coins to the hot wallet automatically without the added liability of requiring that the whole wallet ever be fully decrypted - but that is mostly theoretical at this point. Such a device doesn't exist yet (and we should keep the funds design simple anyway.)

We're actually very lucky with this security model since its probably possible to structure this so that the hot wallet never runs out of funds and the cold wallet for the farmer never has to be thawed out. The same cannot be said for a currency exchange where the best you can achieve is trying to predict future volume and then building lists of timelocked transactions from partitioned cold wallets (which may break if the TXs mutate, thus requiring the wallets to be thawed out again.) We don't have to worry about any of that ugliness with storjnode, although the actual wallet that clients use to pay for contracts is my biggest concern here. 

It is possible to vastly improve the security for storage of SJCX on the client with N-factor authentication by using a redundant multi-signature scheme like the following:

Client 1 pub, Client 2 pub, Client 3 pub, Server 1 pub, Server 2 pub, Timechain or backup pub

4 of 6 multi-signature

This is the scheme I use for Coinbend-style green addresses and it has some very important security properties:
1. The funds can only be unlocked with the client's permission. Or to put it another way: if the server or backup key is simultaneously hacked by another person the user's money is still never at risk (since the attacker still needs a fourth key)
2. N factor authentication can be provided by the server through SMS or something similar (by refusing to sign a client's transaction if the code is incorrect)
3. If the server turns malicious by refusing to sign a valid transaction or if it disappears entirely: a valid timechain can be used to trustlessly unlock the funds in the future (or you can simply replace this key with a frozen backup key of the user's for simplicity)
4. It is possible for the client to lose keys and still have enough leverage to sign (using the server's help.)

This scheme would basically allow client wallets to be virtually unhackable in the majority of cases while strictly eliminating the level of trust that a third-party has over the customer's money. I am not entirely sure what the current design is for the client wallet but this is something to strongly consider if you want SJCX to be resistant to script kiddies (otherwise drive-by exploits or worms could own the user which is still a huge issue in the Bitcoin world)

**Comment by F483** [comment]
No longer needed as all walled data was removed from the config.
